Repository ditrit/leto-modelizer, pull requests merged in 2023-09, with the labels that each got.

#391 Improvement: integrate plugin core 0.20.0
  .github/workflows/CI.yml
  CONTRIBUTING.md
  README.md
  changelog.md
  cypress/e2e/ModelizerPage/SwitchView/AddComponent.feature
  cypress/e2e/ModelsPage/CreateTemplate.feature
  cypress/resources/infra/dev/main.tf
  cypress/resources/infra/prod/main.tf
  cypress/resources/infra1/main.tf
  cypress/resources/infra2/main.tf
  leto-modelizer-plugin-cli.json
  package-lock.json
  package.json
Labels: Technical task

#394 Bugfix: manage root diagram.
  .github/workflows/CI.yml
  CONTRIBUTING.md
  README.md
  changelog.md
  cypress/e2e/Bugfix/Issue377.feature
  leto-modelizer-plugin-cli.json
  package-lock.json
  package.json
  src/components/FileExplorer.vue
  src/components/table/DiagramTable.vue
  src/composables/PluginManager.js
  src/composables/Project.js
  src/layouts/ModelizerDrawLayout.vue
  src/layouts/ModelizerTextLayout.vue
  src/pages/ModelizerDrawPage.vue
  tests/unit/components/FileExplorer.spec.js
  tests/unit/layouts/ModelizerTextLayout.spec.js
Labels: Bug

#359 Feature: Action to rearrange all components
  changelog.md
  cypress/e2e/ModelizerPage/DrawView/plugin/ArrangeComponentsPosition.feature
  cypress/support/step_definitions/html.js
  cypress/support/step_definitions/url.js
  package-lock.json
  package.json
  src/i18n/en-US/index.js
  src/pages/ModelizerDrawPage.vue
  tests/unit/pages/ModelizerDrawPage.spec.js
Labels: enhancement

#400 Release version 1.3.0
  README.md
  changelog.md
  package-lock.json
  package.json
Labels: enhancement
