Repository ditrit/leto-modelizer, pull requests merged in 2023-11, with the labels that each got.

#432 Improvement/git add
  changelog.md
  cypress/e2e/DiagramsPage/DisplayDiagrams.feature
  cypress/e2e/ModelizerPage/SwitchView/Delete.feature
  cypress/e2e/RoundTrips/SimpleProject.feature
  cypress/support/step_definitions/html.js
  src/components/FileExplorer.vue
  src/components/editor/MonacoEditor.vue
  src/components/form/CreateFileForm.vue
  src/components/menu/FileExplorerActionMenu.vue
  src/components/tab/FileTabs.vue
  src/composables/FileExplorer.js
  src/composables/events/FileEvent.js
  src/composables/events/GitEvent.js
  tests/unit/components/FileExplorer.spec.js
  tests/unit/components/editor/MonacoEditor.spec.js
  tests/unit/components/menu/FileExplorerActionMenu.spec.js
  tests/unit/components/tab/FileTabs.spec.js
  tests/unit/composables/FileExplorer.spec.js
  tests/unit/composables/events/FileEvent.spec.js
Labels: :wrench: Refacto

#450 Feature/add rename file folder
  changelog.md
  cypress/e2e/DiagramsPage/DisplayDiagrams.feature
  cypress/e2e/RoundTrips/TextEditor.feature
  package-lock.json
  package.json
  src/components/FileExplorer.vue
  src/components/FileExplorerActionButton.vue
  src/components/dialog/RenameFileDialog.vue
  src/components/form/RenameFileForm.vue
  src/components/menu/FileExplorerActionMenu.vue
  src/components/tab/FileTabs.vue
  src/composables/events/FileEvent.js
  src/i18n/en-US/index.js
  src/layouts/ModelizerTextLayout.vue
  tests/unit/components/FileExplorer.spec.js
  tests/unit/components/FileExplorerActionButton.spec.js
  tests/unit/components/dialog/RenameFileDialog.spec.js
  tests/unit/components/form/RenameFileForm.spec.js
  tests/unit/components/menu/FileExplorerActionMenu.spec.js
  tests/unit/components/tab/FileTabs.spec.js
  tests/unit/composables/events/FileEvent.spec.js
Labels: enhancement

#458 Feature: go to admin
  README.md
  changelog.md
  package-lock.json
  package.json
  quasar.config.js
  src/boot/vue-simple-acl.js
  src/components/menu/ModelizerSettingsMenu.vue
  src/i18n/en-US/index.js
  src/router/index.js
  src/router/routes.js
Labels: Technical task

#460 Fix missing property for adminUrl in quasar config
  quasar.config.js
Labels: Bug

#461 Bugfix/update options link ref
  changelog.md
  cypress/e2e/Bugfix/Issue390.feature
  cypress/e2e/DiagramsPage/DisplayDiagrams.feature
  src/components/inputs/LinkInput.vue
  src/components/inputs/ReferenceInput.vue
  tests/unit/components/inputs/LinkInput.spec.js
  tests/unit/components/inputs/ReferenceInput.spec.js
Labels: Bug
